/*
 * SPDX-FileCopyrightText: Sebastiano Barezzi
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package dev.sebaubuntu.openobd.profiles.models

/**
 * Known car manufacturers.
 *
 * @param displayName The display name
 */
enum class Manufacturer(
    val displayName: String,
) {
    ABARTH("Abarth"),
    ALFA_ROMEO("Alfa Romeo"),
    ASTON_MARTIN("Aston Martin"),
    AUDI("Audi"),
    BENTLEY("Bentley"),
    BMW("BMW"),
    BUGATTI("Bugatti"),
    BUICK("Buick"),
    CADILLAC("Cadillac"),
    CHEVROLET("Chevrolet"),
    CHRYSLER("Chrysler"),
    CITROEN("Citroen"),
    DACIA("Dacia"),
    DAEWOO("Daewoo"),
    DAIHATSU("Daihatsu"),
    DODGE("Dodge"),
    DONKERVOORT("Donkervoort"),
    DS("DS"),
    FERRARI("Ferrari"),
    FIAT("Fiat"),
    FISKER("Fisker"),
    FORD("Ford"),
    HONDA("Honda"),
    HUMMER("Hummer"),
    HYUNDAI("Hyundai"),
    INFINITI("Infiniti"),
    ISUZU("Isuzu"),
    IVECO("Iveco"),
    JAGUAR("Jaguar"),
    JEEP("Jeep"),
    KIA("Kia"),
    KOENIGSEGG("Koenigsegg"),
    KTM("KTM"),
    LADA("Lada"),
    LAMBORGHINI("Lamborghini"),
    LANCIA("Lancia"),
    LAND_ROVER("Land Rover"),
    LANDWIND("Landwind"),
    LEXUS("Lexus"),
    LOTUS("Lotus"),
    MASERATI("Maserati"),
    MAYBACH("Maybach"),
    MAZDA("Mazda"),
    MCLAREN("McLaren"),
    MERCEDES_BENZ("Mercedes-Benz"),
    MG("MG"),
    MINI("Mini"),
    MITSUBISHI("Mitsubishi"),
    MORGAN("Morgan"),
    NISSAN("Nissan"),
    OPEL("Opel"),
    PAGANI("Pagani"),
    PEUGEOT("Peugeot"),
    PONTIAC("Pontiac"),
    PORSCHE("Porsche"),
    RAM("Ram"),
    RANGE_ROVER("Range Rover"),
    RENAULT("Renault"),
    RIVIAN("Rivian"),
    ROLLS_ROYCE("Rolls-Royce"),
    SAAB("Saab"),
    SEAT("SEAT"),
    SKODA("Skoda"),
    SMART("Smart"),
    SSANGYONG("SsangYong"),
    SUBARU("Subaru"),
    SUZUKI("Suzuki"),
    TESLA("Tesla"),
    TOYOTA("Toyota"),
    VOLKSWAGEN("Volkswagen"),
    VOLVO("Volvo"),
    OTHER("Other"),
}
